version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/deployexample/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/fileprovider/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/msitools/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/vpnconnect/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/windowsdeployer/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/docker/fileprovider/"
    schedule:
      interval: "daily" 
  - package-ecosystem: "pip"
    directory: "/docker/vpnconnect/"
    schedule:
      interval: "daily" 
  - package-ecosystem: "pip"
    directory: "/docker/windowsdeployer/"
    schedule:
      interval: "daily" 
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/docker/deployexample/"
    schedule:
      interval: "daily"